title: Root and Steel
description: Root and Steel SRD
theme: just-the-docs

url: https://PastelGF.github.io/rootandsteel

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/PastelGF/rootandsteel

color_scheme: dark
